N_EPISODES: 10_000_000
INITIAL_BANKROLL: 100
GAMMA: 0.99
LR: 0.001
EPSILON_START: 1.0
EPSILON_END: 0.01
EPSILON_DECAY: 0.999995
BATCH_SIZE: 64
MEMORY_SIZE: 100_000
TARGET_UPDATE_FREQ: 100
DUELING: False
RENDER: false