N_EPISODES: 100000
INITIAL_BANKROLL: 500
GAMMA: 0.95
LR: 0.0007
EPSILON_START: 1.0
EPSILON_END: 0.05
EPSILON_DECAY: 0.9999
BATCH_SIZE: 32
MEMORY_SIZE: 75000
TARGET_UPDATE_FREQ: 150
DUELING: false
RENDER: false